# Nombre de la aplicación Spring
spring.application.name=CometaApp-h2

# Puerto donde se ejecutará el servidor
server.port=8080

# Credenciales de la base de datos H2
spring.datasource.username=SA
spring.datasource.password=

# Configuración para el manejo del esquema de la base de datos con JPA:
# create-drop: Se crea el esquema al iniciar la aplicación y se elimina al cerrarla.
spring.jpa.hibernate.ddl-auto=create-drop

# Habilita la visualización de las sentencias SQL generadas por JPA en la consola
spring.jpa.show-sql=true

# URL de conexión a la base de datos en memoria H2
spring.datasource.url=jdbc:h2:mem:cometa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Habilita la consola web de H2 para consultas sobre la base de datos
spring.h2.console.enabled=true

# Ruta de acceso para la consola H2
spring.h2.console.path=/h2-console

# Driver de la base de datos H2
spring.datasource.driver-class-name=org.h2.Driver

# Configuración de endpoints de monitoreo:
# Se exponen los endpoints de health, info y metrics a través de la web
#management.endpoints.web.exposure.include=health,info,metrics
management.endpoints.web.exposure.include=*

# Incluye detalles del entorno en el endpoint `info`
management.info.env.enabled=true

# Ejemplo comentado para exponer únicamente el endpoint `info`
# management.endpoints.web.exposure.include=info

# Información personalizada para mostrar en el endpoint `info`
info.name=CometaApp-h2
info.version=1.0.0
info.precio=10
info.email=algo@alguie.com
info.celular=33-12345678
info.persona.nombre=jose
info.persona.segundo_nombre=said

# Email configurable usando propiedades del sistema o variables de entorno.
# Usa josesaid@gmail.com de forma predeterminada si no se configura explícitamente
info.persona.email=${EMAIL:josesaid@gmail.com}

# URL del servidor Spring Boot Admin para la administración de clientes
spring.boot.admin.client.url=http://localhost:8123

# URL completa donde corre este cliente, necesaria para que Spring Boot Admin registre
# correctamente la instancia
spring.boot.admin.client.instance.service-base-url=http://localhost:8080

# Habilita el registro