spring.application.name=Lesson16-ms-pedidos
server.port=8084

spring.boot.admin.client.instance.service-base-url=http://localhost:8084
spring.boot.admin.client.url=http://localhost:8123

management.info.env.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
