version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: cometa_postgres
    environment:
      POSTGRES_DB: CometaSecurityApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - cometa_network

networks:
  cometa_network:
